### ISSUE TITLE
Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by sorenc49** [1024pix/pix#8637]
Bonjour, j'ai un problème, juste après le deuxième "Using environment: development"

cela m'affiche ça 

Cannot read properties of undefined (reading 'bind')
TypeError: Cannot read properties of undefined (reading 'bind')
    at new RedisClient (file:///C:/Users/Utilisateur/Documents/pix/pix/api/lib/infrastructure/utils/RedisClient.js:36:55)
    at new DistributedCache (file:///C:/Users/Utilisateur/Documents/pix/pix/api/lib/infrastructure/caches/DistributedCache.js:11:34)
    at new LearningContentCache (file:///C:/Users/Utilisateur/Documents/pix/pix/api/lib/infrastructure/caches/learning-content-cache.js:13:32)
    at LearningContentCache.defaultInstance (file:///C:/Users/Utilisateur/Documents/pix/pix/api/lib/infrastructure/caches/learning-content-cache.js:45:12)
    at get instance [as instance] (file:///C:/Users/Utilisateur/Documents/pix/pix/api/lib/infrastructure/caches/learning-content-cache.js:50:29)
    at file:///C:/Users/Utilisateur/Documents/pix/pix/api/lib/infrastructure/caches/learning-content-cache.js:60:58
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async FsSeeds.getSeed (C:\Users\Utilisateur\Documents\pix\pix\node_modules\knex\lib\migrations\seed\sources\fs-seeds.js:58:18)
    at async Seeder._validateSeedStructure (C:\Users\Utilisateur\Documents\pix\pix\node_modules\knex\lib\migrations\seed\Seeder.js:55:18)
    at async Seeder._runSeeds (C:\Users\Utilisateur\Documents\pix\pix\node_modules\knex\lib\migrations\seed\Seeder.js:49:7)
    
    Pouvez vous m'aider ??

**Comment by MelanieMEB** [comment]
Bonjour, 

En première lecture, il semblerait que votre installation avec Redis ne fonctionne pas. 
Avez-pu lancer votre Redis et bien indiquer dans les variables d'env le `REDIS_URL` ? 

Le repository Pix a pour vocation de développer uniquement les besoins de Pix, et l’installation de la plateforme ainsi que son évolution via un fork peut être complexe.
Merci de contacter [engineering-fork@pix.fr](mailto:engineering-fork@pix.fr) pour nous partager ce que vous souhaitez faire en installant Pix, pour pouvoir vous aider au mieux.
Nous rappelons aussi que ce logiciel et son code source sont distribués sous [licence AGPL](https://www.gnu.org/licenses/why-affero-gpl.fr.html).
