### ISSUE TITLE
Erreur de fetching via http-agent

### ISSUE THREAD

**Issue by theotime2005** [1024pix/pix#9412]
# Problème
Lorsqu'on utilise http-agent la réponse renvoyée est fausse et induit l'API en erreur.

# Pour reproduire
- Ouvrir le fichier api/src/prescription/campaign/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
- Exécuter le fichier de test associé: api/tests/prescription/campaign/integration/infrastructure/repositories/campaign-administration-repository_test.js
Voici ce que j'ai obtenu:
```shel
{"level":30,"time":1719826999860,"pid":11669,"hostname":"MacBook-Pro-de-Theotime.local","event":"cache-event","key":"LearningContent","msg":"Cannot found the key from the firstLevelCache. Fetching on the second one."}
{"level":30,"time":1719826999863,"pid":11669,"hostname":"MacBook-Pro-de-Theotime.local","key":"LearningContent","msg":"Executing generator for Redis key"}
{"level":50,"time":1719826999866,"pid":11669,"hostname":"MacBook-Pro-de-Theotime.local","user_id":"-","request_id":"-","metrics":{"responseTime":3.5363750000001346},"msg":"End GET request to https://lcms.minimal.pix.fr/api/releases/latest error: 500 null"}
{"level":50,"time":1719826999868,"pid":11669,"hostname":"MacBook-Pro-de-Theotime.local","err":{"type":"Error","message":"An error occurred while fetching https://lcms.minimal.pix.fr/api","stack":"Error: An error occurred while fetching https://lcms.minimal.pix.fr/api\n    at Object.getLatestRelease (file:///Users/theotime/dev/pix/principal_pix/api/lib/infrastructure/lcms.js:22:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async retrieveAndSetValue (file:///Users/theotime/dev/pix/principal_pix/api/lib/infrastructure/caches/RedisCache.js:43:21)"},"msg":"Error while trying to update value in Redis cache"}
{"level":30,"time":1719826999870,"pid":11669,"hostname":"MacBook-Pro-de-Theotime.local","msg":"Flushing Redis database"}
{"level":30,"time":1719826999873,"pid":11669,"hostname":"MacBook-Pro-de-Theotime.local","event":"cache-event","msg":"Flushing the local cache"}

Error: An error occurred while fetching https://lcms.minimal.pix.fr/api
    at Object.getLatestRelease (file:///Users/theotime/dev/pix/principal_pix/api/lib/infrastructure/lcms.js:22:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retrieveAndSetValue (file:///Users/theotime/dev/pix/principal_pix/api/lib/infrastructure/caches/RedisCache.js:43:21)
```

**Comment by VincentHardouin** [comment]
Ton test a l'air d'appeler la vrai implémentation, je pense que le problème vient plutôt de `nock` qui est mal configuré

**Comment by theotime2005** [comment]
# Situation
C'est l'environnement d'exécution du teste qui n'étais pas bon.

# Condition de teste
Le teste était exécuté avec Webstorm depuis l'IDE.

# Correction
Dans le menu Run, faire "Edit configuration". Là, coller le texte suivant dans la zone "Environment variables:":
```shell
NODE_ENV=test
```
Le teste devrait alors passer normalement.
